version: '2'

services:

  bootstrap:
    image: holochain/holochain-proto:develop
    ports:
      - "3142:3142"
    command: bs

  proto1:
    image: holochain/holochain-proto:develop
    ports:
      - "3141:3141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/proto"
    command: bash -c "cd /proto; HCLOG_DHT_ENABLE=1 hcdev -DHTport=6001 -agentID=lucy -bootstrapServer=bootstrap:3142 web 3141"

  proto2:
    image: holochain/holochain-proto:develop
    ports:
      - "4141:4141"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/proto"
    command: bash -c "cd /proto; HCLOG_DHT_ENABLE=1 hcdev -DHTport=6002 -agentID=phil -bootstrapServer=bootstrap:3142 web 4141"
